(function(p){function l(d,c,b,k){if("string"!=typeof d)throw"System.register provided no module name";c="boolean"==typeof b?{declarative:!1,deps:c,execute:k,executingRequire:b}:{declarative:!0,deps:c,declare:b};c.name=d;d in m||(m[d]=c);d=c.deps;b=[];k=0;for(var f=d.length;k<f;k++)-1==q.call(b,d[k])&&b.push(d[k]);c.deps=b;c.normalizedDeps=c.deps}function g(d,c){c[d.groupIndex]=c[d.groupIndex]||[];if(-1==q.call(c[d.groupIndex],d)){c[d.groupIndex].push(d);for(var b=0,f=d.normalizedDeps.length;b<f;b++){var e=
m[d.normalizedDeps[b]];if(e&&!e.evaluated){var a=d.groupIndex+(e.declarative!=d.declarative);if(void 0===e.groupIndex||e.groupIndex<a){if(void 0!==e.groupIndex&&(c[e.groupIndex].splice(q.call(c[e.groupIndex],e),1),0==c[e.groupIndex].length))throw new TypeError("Mixed dependency cycle detected");e.groupIndex=a}g(e,c)}}}}function a(d){return x[d]||(x[d]={name:d,dependencies:[],exports:{},importers:[]})}function h(d){if(!d.module){var c=d.module=a(d.name),b=d.module.exports,e=d.declare.call(p,function(e,
d){c.locked=!0;b[e]=d;for(var f=0,n=c.importers.length;f<n;f++){var a=c.importers[f];if(!a.locked){var k=q.call(a.dependencies,c);a.setters[k](b)}}c.locked=!1;return d});c.setters=e.setters;c.execute=e.execute;if(!c.setters||!c.execute)throw new TypeError("Invalid System.register form for "+d.name);for(var e=0,g=d.normalizedDeps.length;e<g;e++){var t=d.normalizedDeps[e],n=m[t],r=x[t];r?t=r.exports:n&&!n.declarative?t=n.module.exports&&n.module.exports.__esModule?n.module.exports:{"default":n.module.exports,
__useDefault:!0}:n?(h(n),r=n.module,t=r.exports):t=f(t);r&&r.importers?(r.importers.push(c),c.dependencies.push(r)):c.dependencies.push(null);if(c.setters[e])c.setters[e](t)}}}function b(d){if(!d.module){var c={},a=d.module={exports:c,id:d.name};if(!d.executingRequire)for(var k=0,g=d.normalizedDeps.length;k<g;k++){var h=m[d.normalizedDeps[k]];h&&b(h)}d.evaluated=!0;if(c=d.execute.call(p,function(c){for(var a=0,k=d.deps.length;a<k;a++)if(d.deps[a]==c){c=d.normalizedDeps[a];a=void 0;if(k=m[c])k.declarative?
e(c,[]):k.evaluated||b(k),a=k.module.exports;else if(a=f(c),!a)throw Error("Unable to load dependency "+c+".");c=(!k||k.declarative)&&a&&a.__useDefault?a["default"]:a;return c}throw new TypeError("Module "+c+" not declared as a dependency.");},c,a))a.exports=c}}function e(d,c){var b=m[d];if(b&&!b.evaluated&&b.declarative){c.push(d);for(var a=0,g=b.normalizedDeps.length;a<g;a++){var h=b.normalizedDeps[a];-1==q.call(c,h)&&(m[h]?e(h,c):f(h))}b.evaluated||(b.evaluated=!0,b.module.execute.call(p))}}function f(d){if(w[d])return w[d];
var c=m[d];if(!c)throw"Module "+d+" not present.";var a=m[d];a.groupIndex=0;var f=[];g(a,f);for(var a=!!a.declarative==f.length%2,q=f.length-1;0<=q;q--){for(var l=f[q],n=0;n<l.length;n++){var r=l[n];a?h(r):b(r)}a=!a}e(d,[]);m[d]=void 0;f=c.module.exports;if(!f||!c.declarative&&!0!==f.__esModule)f={"default":f,__useDefault:!0};return w[d]=f}var m={},q=Array.prototype.indexOf||function(b){for(var c=0,a=this.length;c<a;c++)if(this[c]===b)return c;return-1},x={},w={};return function(b,c){var a;a={register:l,
get:f,set:function(a,b){w[a]=b},newModule:function(a){return a},global:p};a.set("@empty",{});c(a);for(a=0;a<b.length;a++)f(b[a])}})("undefined"!=typeof window?window:global)(["cam-frame"],function(p){p.register("platform",[],function(l){var g;return{setters:[],execute:function(){g=window.navigator.userAgent.includes("Macintosh");l("default",{IS_MAC:g,isExtension:!!chrome.runtime.id,isTopFrame:window.top===window})}}});p.register("w69b/async-response",[],function(l){l("createSender",function(g){var a=
{},h=0,b={};a.sendWithResponse=function(a,f){return new Promise(function(m,q){var l=++h;b[l]=[m,q];g({type:a,data:f,msgId:l})})};a.send=function(a,b){g({type:a,data:b})};a.handleResult=function(a){if(a&&"result"===a.type){var f=b[a.msgId];delete b[a.msgId];if(a.hasOwnProperty("error")||a.isError)f[1](a.error);else f[0](a.data);return!0}return!1};return a});l("createRespond",function(g){return function(a,h){Promise.resolve(a).then(function(a){g({type:"result",msgId:h.msgId,data:a})},function(a){g({type:"result",
msgId:h.msgId,error:a,isError:!0})})}});return{setters:[],execute:function(){}}});p.register("w69b/q",[],function(l){var g;return{setters:[],execute:function(){g={defer:function(){var a={};a.promise=new Promise(function(h,b){a.resolve=h;a.reject=b});return a}};g.when=Promise.resolve.bind(Promise);g.all=Promise.all.bind(Promise);g.reject=Promise.reject.bind(Promise);Promise.prototype.finally||(Promise.prototype.finally=function(a){var h=this.constructor;return this.then(function(b){return h.resolve(a()).then(function(){return b})},
function(b){return h.resolve(a()).then(function(){throw b;})})});l("default",g)}}});p.register("chrome-messaging",[],function(l){function g(a){return a instanceof Error?Promise.reject(a.toString()):Promise.reject(a)}l("sendMessage",function(a,h){return new Promise(function(b,e){chrome.runtime.sendMessage({type:a,data:h},function(a){chrome.runtime.lastError?e(chrome.runtime.lastError):a?"result"===a.type?b(a.data):"error"===a.type&&e(a.data):e()})})});l("respond",function(a,h){Promise.resolve(h).catch(g).then(function(b){a({type:"result",
data:b})},function(b){a({type:"error",data:b})})});return{setters:[],execute:function(){}}});p.register("w69b/promise-tool",["w69b/q"],function(l){var g,a;return{setters:[function(a){g=a.default}],execute:function(){a={wrapChromeError:function(a,b){return function(){var e=Array.prototype.slice.call(arguments,0),f=g.defer();e.push(function(a){chrome.runtime.lastError?f.reject(chrome.runtime.lastError):f.resolve(a)});a.apply(b,e);return f.promise}},wrapCallbacks:function(a,b){return function(){var e=
Array.prototype.slice.call(arguments,0),f=g.defer();e.push(f.resolve.bind(f));e.push(f.reject.bind(f));a.apply(b,e);return f.promise}}};l("default",a)}}});p.register("w69b/webrtc",["w69b/promise-tool","w69b/q"],function(l){function g(a){return a.some(function(a){return!!a.label})}var a,h,b,e;return{setters:[function(b){a=b.default},function(a){h=a.default}],execute:function(){b={};e=window.navigator;b.getUserMedia=e.mediaDevices&&e.mediaDevices.getUserMedia?e.mediaDevices.getUserMedia.bind(e.mediaDevices):
a.wrapCallbacks(e.getUserMedia||e.webkitGetUserMedia||e.mozGetUserMedia||e.msGetUserMedia,e);b.getSources=e.mediaDevices&&e.mediaDevices.enumerateDevices?function(){return h.when(e.mediaDevices.enumerateDevices()).then(function(a){return a.filter(function(a){return a.kind.endsWith("input")}).map(function(a){var b={id:a.deviceId,label:a.label};b.kind=a.kind.substring(0,a.kind.length-5);return b})})}:window.MediaStreamTrack&&MediaStreamTrack.getSources?a.wrapCallbacks(MediaStreamTrack.getSources,MediaStreamTrack):
function(){return Promise.resolve([])};b.getSourcesByKind=function(a){return b.getSources().then(function(b){return b.filter(function(b){return b.kind===a})})};b.getVideoSources=function(){return b.getSourcesByKind("video")};b.getAudioSources=function(){return b.getSourcesByKind("audio")};b.hasCamera=function(){return b.getVideoSources().then(function(a){return 0<a.length})};b.hasMicrophone=function(){return b.getAudioSources().then(function(a){return 0<a.length})};b.hasVideoAccess=function(){return b.getVideoSources().then(g)};
b.hasAudioAccess=function(){return b.getAudioSources().then(g)};l("default",b)}}});p.register("cam-frame",["platform","w69b/async-response","w69b/webrtc","chrome-messaging"],function(l){function g(){function g(){c.pause();URL.revokeObjectURL(u);u=null;k.getTracks().forEach(function(a){a.stop()});k=null}function l(a,b,c){return a&&a.type===m&&(a=a.data)&&v.hasOwnProperty(a.type)?(e.respond(c,v[a.type](a.data)),!0):!1}function p(a){return a instanceof Error?Promise.reject(a.toString()):Promise.reject(a)}
function d(a){a=a.data;if(v.hasOwnProperty(a.type)){var b=Promise.resolve(v[a.type](a.data)).catch(p);t(b,a)}}var c,u,k,v={start:function(a){k&&g();return b.getUserMedia({video:a}).then(function(a){k=a;a=new Promise(function(a){c||(c=document.createElement("video"),c.volume=0,document.body.appendChild(c));c.addEventListener("canplay",function y(){c.removeEventListener("canplay",y);a({width:c.videoWidth,height:c.videoHeight})})});u=URL.createObjectURL(k);c.src=u;c.play();return a})},stop:function(){g()},
getVideoDevices:function(){return b.getVideoSources()}},t=h.createRespond(function(a){window.parent.postMessage(a,window.location.origin)});a.isExtension?chrome.runtime.onMessage.addListener(l):(console.debug("camFrame: using dev-only messaging"),window.addEventListener("message",d));window.parent.postMessage(f,"*")}var a,h,b,e,f,m;return{setters:[function(b){a=b.default},function(a){h=a},function(a){b=a.default},function(a){e=a}],execute:function(){f="castifyDrawCamFrameReady";m="camFrameMsgWithResult";
g()}}})});
